### ISSUE TITLE
ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by fyyakaxyy** [EricGuo5513/text-to-motion#30]
Hello, I would like to evaluate the pre trained model on t2m, but it reported an error as follows. How can I resolve this issue?

```
(motiondiffuse) ubuntu@ubuntu:~/fyy/text-to-motion$ python final_evaluations.py 
Reading ./checkpoints/t2m/Comp_v6_KLD01/opt.txt
Loading dataset t2m ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4384/4384 [00:00<00:00, 6065.30it/s]
4648
4648
Pointer Pointing at 0
Ground Truth Dataset Loading Completed!!!
Reading ./checkpoints/t2m/Comp_v6_KLD01/opt.txt
Loading Evaluation Model Wrapper (Epoch 28) Completed!!
Reading ./checkpoints/t2m/Comp_v6_KLD01/opt.txt
Generating Comp_v6_KLD01 ...
./checkpoints/t2m/Comp_v6_KLD01/model
Loading model: Epoch 344 Schedule_len 049
4648it [01:22, 56.16it/s]
Generated Dataset Loading Completed!!!
==================== Replication 0 ====================
Time: 2023-08-08 22:12:23.306905
========== Evaluating Matching Score ==========
---> [ground truth] Matching Score: nan
---> [ground truth] R_precision: (top 1): 0.5162 (top 2): 0.7088 (top 3): 0.8015 
---> [Comp_v6_KLD01] Matching Score: 3.4038
---> [Comp_v6_KLD01] R_precision: (top 1): 0.4524 (top 2): 0.6278 (top 3): 0.7254 
Time: 2023-08-08 22:12:27.198547
========== Evaluating FID ==========
Traceback (most recent call last):
  File "final_evaluations.py", line 319, in <module>
    evaluation(log_file)
  File "final_evaluations.py", line 172, in evaluation
    fid_score_dict = evaluate_fid(gt_loader, acti_dict, f)
  File "final_evaluations.py", line 101, in evaluate_fid
    fid = calculate_frechet_distance(gt_mu, gt_cov, mu, cov)
  File "/home/ubuntu/fyy/text-to-motion/utils/metrics.py", line 128, in calculate_frechet_distance
    covmean, _ = linalg.sqrtm(sigma1.dot(sigma2), disp=False)
  File "/home/ubuntu/anaconda3/envs/motiondiffuse/lib/python3.8/site-packages/scipy/linalg/_matfuncs_sqrtm.py", line 161, in sqrtm
    A = _asarray_validated(A, check_finite=True, as_inexact=True)
  File "/home/ubuntu/anaconda3/envs/motiondiffuse/lib/python3.8/site-packages/scipy/_lib/_util.py", line 287, in _asarray_validated
    a = toarray(a)
  File "/home/ubuntu/anaconda3/envs/motiondiffuse/lib/python3.8/site-packages/numpy/lib/function_base.py", line 488, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs
```

**Comment by zhangerhang** [comment]
I meet the same question.Have you sovled the problem?

**Comment by AnanyaBal** [comment]
Has this issue been resolved? Simply running final_evaluations.py on provided checkpoints is leading to NaNs for FID
