### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by khansharkhamnida** [EricGuo5513/text-to-motion#40]
100%|█████████████████████████████████████████████████████████████████████████| 23384/23384 [00:00<00:00, 154772.68it/s]
Traceback (most recent call last):
  File "train_comp_v6.py", line 146, in <module>
    train_dataset = Text2MotionDataset(opt, mean, std, train_split_file, w_vectorizer)
  File "/home/nsazielle/Synthda/text-to-motion/data/dataset.py", line 91, in __init__
    name_list, length_list = zip(*sorted(zip(new_name_list, length_list), key=lambda x: x[1]))
ValueError: not enough values to unpack (expected 2, got 0)

any idea why this happened?

**Comment by EricGuo5513** [comment]
Hi, check if you have the correctly load the data, e.g., data path.

**Comment by khansharkhamnida** [comment]
![image](https://github.com/EricGuo5513/text-to-motion/assets/52180702/6848c664-56f4-4293-a060-e3276d38d701)
![image](https://github.com/EricGuo5513/text-to-motion/assets/52180702/c58398d8-62f1-4380-af7d-3fa6cd7cf3a5)

i think it's right? i was following the instructions

**Comment by khansharkhamnida** [comment]
![image](https://github.com/EricGuo5513/text-to-motion/assets/52180702/acaf2540-6f8a-428c-ad04-b940680ac833)
i think i might have found out the issue. There's only one npy file here. where do i get the rest? i cloned https://github.com/EricGuo5513/HumanML3D and took only the HumanML3D folder inside. I didn't follow the instructions. How should I proceed with this

**Comment by roobte** [comment]
请问上述问题解决了么？？应该如何处理呢？？？

**Comment by SHO252** [comment]
Hi @khansharkhamnida, it looks like you’re missing the precomputed joint vectors. You can fix this by:

Downloading the new_joint_vecs.rar archive from
https://drive.google.com/drive/folders/1OZrTlAGRvLjXhXwnRiOC-oxYry1vf-Uu

Placing the downloaded new_joint_vecs.rar into your dataset/HumanML3D/ folder, then running:

cd dataset/HumanML3D/
unrar x new_joint_vecs.rar new_joint_vecs/

After that, your Text2MotionDataset loader will find the extra .npy files and the error should go away!

**Comment by yuf-gpu** [comment]
> 请问上述问题解决了么？？应该如何处理呢？？？

请你检查一下texts.rar文件是否解压缩，我是这个没有解压缩报错的
