### ISSUE TITLE
Evaluation failure

### ISSUE THREAD

**Issue by GuyTevet** [EricGuo5513/text-to-motion#6]
Thanks for your great work!
Running with your conda env (ubuntu18), the script `final_evaluations.py` fails with:

`python final_evaluations.py`

```
Reading ./checkpoints/t2m/Comp_v6_KLD01/opt.txt
Loading dataset t2m ...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 830/830 [00:00<00:00, 952.81it/s]
Pointer Pointing at 0
Ground Truth Dataset Loading Completed!!!
Reading ./checkpoints/t2m/Comp_v6_KLD01/opt.txt
Loading Evaluation Model Wrapper (Epoch 28) Completed!!
Reading ./checkpoints/t2m/Comp_v6_KLD01/opt.txt
Generating Comp_v6_KLD01 ...
./checkpoints/t2m/Comp_v6_KLD01/model
Loading model: Epoch 344 Schedule_len 049
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "final_evaluations.py", line 318, in <module>
    evaluation(log_file)
  File "final_evaluations.py", line 160, in evaluation
    motion_loader, mm_motion_loader = motion_loader_getter()
  File "final_evaluations.py", line 281, in <lambda>
    batch_size, gt_dataset, mm_num_samples, mm_num_repeats, device
  File "/disk1/guytevet/text-to-motion/motion_loaders/model_motion_loaders.py", line 60, in get_motion_loader
    dataset = CompV6GeneratedDataset(opt, ground_truth_dataset, w_vectorizer, mm_num_samples, mm_num_repeats)
  File "/disk1/guytevet/text-to-motion/motion_loaders/comp_v6_model_dataset.py", line 73, in __init__
    for i, data in tqdm(enumerate(dataloader)):
  File "/disk2/guytevet/anaconda3/envs/text2motion_pub/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/disk2/guytevet/anaconda3/envs/text2motion_pub/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/disk2/guytevet/anaconda3/envs/text2motion_pub/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/disk2/guytevet/anaconda3/envs/text2motion_pub/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/disk2/guytevet/anaconda3/envs/text2motion_pub/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/disk2/guytevet/anaconda3/envs/text2motion_pub/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/disk2/guytevet/anaconda3/envs/text2motion_pub/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk2/guytevet/anaconda3/envs/text2motion_pub/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk1/guytevet/text-to-motion/data/dataset.py", line 335, in __getitem__
    motion = (motion - self.mean) / self.std
ValueError: operands could not be broadcast together with shapes (104,251) (263,)
```

**Comment by GuyTevet** [comment]
My bad! I was pointing kit instead of HumanML
